settings_default:
  weights: 'yolov4.pt'    # model.pt path(s)
  source: 'data/images'   # file/dir/URL/glob, 0 for webcam
  imgsz: [640]            # inference size (pixels)
  conf_thres: 0.25        # confidence threshold
  iou_thres: 0.45         # NMS IOU threshold
  max_det: 300            # maximum detections per image
  device: ''              # cuda device, i.e. 0 or 0,1,2,3 or cpu
  view_img: 0             # show results
  save_txt: 0             # save results to *.txt
  save_conf: 0            # save confidences in --save-txt labels
  save_crop: 0            # save cropped prediction boxes
  nosave: 0               # do not save images/videos
  classes: None           # filter by class: --class 0, or --class 0 2 3
  agnostic_nms: 0         # class-agnostic NMS
  augment: 0              # augmented inference
  visualize: 0            # visualize features
  update: 0               # update all models
  project: 'runs/detect'  # save results to project/name
  name: 'exp'             # save results to project/name
  exist_ok: 0             # existing project/name ok, do not increment
  line_thickness: 3       # bounding box thickness (pixels)
  hide_labels: 0          # hide labels
  hide_conf: 0            # hide confidences
  half: 0                 # use FP16 half-precision inference
  library: None           # for khadas
  auto: 1                 # auto is for dynamic models but for static models turn this 0
  opencv_onnx: 0          # are you using opencv to load onnx models?
  scalefill: 0            # if you want your images to be a strench resize as an input

settings:
  weights: '../weights/yolov4-csp-640-640-herdial/yolov4-csp-640-640-herdial.nb'
  source: '0'
  imgsz: [640]
  conf_thres: 0.4
  iou_thres: 0.45
  max_det: 300
  device: ''
  view_img: 0
  save_txt: 1
  save_conf: 0
  save_crop: 0
  nosave: 0
  classes: 'None'
  agnostic_nms: 0
  augment: 0
  visualize: 0
  update: 0
  project: 'runs/detect'
  name: 'exp'
  exist_ok: 0
  line_thickness: 3
  hide_labels: 0
  hide_conf: 0
  half: 0
  library: '../weights/yolov4-csp-640-640-herdial/libnn_yolov4-csp-640-640-herdial.so'
  auto: 0
  opencv_onnx: 0 
  scalefill: 1

# weights: '../weights/yolov4-csp-all-environment-640/yolov4-csp-all-environment-640.nb'
# library: '../weights/yolov4-csp-all-environment-640/libnn_yolov4-csp-all-environment-640.so'